
{% set column_names = [
"TERM_NUMBER",
"YTD_GROSS_WRITTEN_PREMIUM_AMT",
"YTD_GROSS_EARNED_PREMIUM_AMT",
"YTD_NEW_BUSINESS_WRITTEN_PREMIUM_AMT",
"YTD_CANCELLED_PREMIUM_AMT",
"YTD_LAPSED_PREMIUM_AMT",
"YTD_COMMISSION_AMT",
"YTD_RENEWABLE_PREMIUM_AMT",
"YTD_RETENTION_PREMIUM_AMT",
"RENEWABLE_FLG",
"RETENTION_FLG",
"CANCELLED_FLG",
"LAPSED_FLG",
"NB_POLICY_FLG",
"INFORCE_FLG",
"POLICY_EFFECTIVE_DATE",
"POLICY_EXPIRY_DATE",
"FUNCTIONAL_ENTITY_DIM_KEY",
"BUSINESS_TYPE_DIM_KEY",
"MARKET_DIMENSION_DIM_KEY",
"CUSTOMER_SEGMENT_DIM_KEY",
"BUSINESS_SECTOR_DIM_KEY",
"LINE_OF_BUSINESS_DIM_KEY",
"DURABLE_BROKER_HIERARCHY_KEY",
"CURRENCY_DIM_KEY",
"DIM_POLICY_TERM_KEY",
"DIM_PROGRAM_CODE_DESC_KEY",
"YTD_INFORCE_PREMIUM_AMT"
] %}
{% set summarize = true %}

{% set a_query %}      
SELECT distinct concat_ws('|' , FP.ACCOUNTING_MONTH_KEY, DPT.POLICY_NUMBER, FP.DIM_POLICY_TERM_KEY, COI.LINE_OF_BUSINESS_DIM_KEY) as primary_id,
 FP.ACCOUNTING_MONTH_KEY
 ,DPT.POLICY_NUMBER
 , DPT.TERM_NUMBER
 ,SUM(
 	  COALESCE(FP.YTD_DIRECT_PREMIUM_WRITTEN_AMT,0)
 	+ COALESCE(FP.YTD_ASSUMED_PREMIUM_WRITTEN_AMT,0)
   ) AS YTD_GROSS_WRITTEN_PREMIUM_AMT
 , SUM(COALESCE(FP.YTD_DIRECT_PREMIUM_EARNED_AMT,0)+ COALESCE(FP.YTD_ASSUMED_PREMIUM_EARNED_AMT,0)) AS YTD_GROSS_EARNED_PREMIUM_AMT
 , SUM( CASE WHEN DPTP.NEW_BUSINESS_IND = 'Y'
   THEN COALESCE(FP.YTD_DIRECT_PREMIUM_WRITTEN_AMT,0) + COALESCE(FP.YTD_ASSUMED_PREMIUM_WRITTEN_AMT,0) ELSE 0 END ) AS YTD_NEW_BUSINESS_WRITTEN_PREMIUM_AMT
 ,SUM(CASE WHEN DPTP.CANCELLED_IND = 'Y'
  THEN COALESCE (FP.YTD_DIRECT_PREMIUM_WRITTEN_AMT,0) + COALESCE (FP.YTD_ASSUMED_PREMIUM_WRITTEN_AMT,0) ELSE 0 END) AS  YTD_CANCELLED_PREMIUM_AMT
 
 ,SUM(CASE WHEN DPTP.LAPSED_IND = 'Y'
  THEN COALESCE (FP.YTD_DIRECT_PREMIUM_WRITTEN_AMT,0) +
  COALESCE (FP.YTD_ASSUMED_PREMIUM_WRITTEN_AMT,0) ELSE 0 END) AS  YTD_LAPSED_PREMIUM_AMT

 ,SUM(COALESCE(FP.YTD_DIRECT_COMMISSION_AMT,0) + COALESCE(FP.YTD_ASSUMED_COMMISSION_AMT,0)) AS YTD_COMMISSION_AMT
 , SUM(COALESCE(R.YTD_RENEW_GWP,0)) AS YTD_RENEWABLE_PREMIUM_AMT
 , SUM(COALESCE(R.YTD_RETN_GWP,0))  AS YTD_RETENTION_PREMIUM_AMT

 ,CASE WHEN R.RENEWABLE_IND ='Y' THEN 1 ELSE 0 END AS RENEWABLE_FLG
 
 ,CASE WHEN COALESCE(R.YTD_RETN_GWP,0)> 0 THEN 1 ELSE 0 END AS RETENTION_FLG

 , CASE WHEN DPTP.CANCELLED_IND ='Y' THEN 1 ELSE 0 END AS CANCELLED_FLG 
 , CASE WHEN DPTP.LAPSED_IND ='Y' THEN 1 ELSE 0 END AS LAPSED_FLG 

 , CASE WHEN DPTP.NEW_BUSINESS_IND ='Y' THEN 1 ELSE 0 END AS NB_POLICY_FLG
 , CASE  WHEN FAC.DIM_POLICY_TERM_KEY IS NOT NULL AND  FAC.MTD_POLICY_INFORCE_CNT = 1 THEN 1 ELSE 0 END AS INFORCE_FLG
 , DPT.POLICY_EFFECTIVE_DATE
 
 , DPT.POLICY_EXPIRY_DATE
 , FP.FUNCTIONAL_ENTITY_DIM_KEY 
 , FP.BUSINESS_TYPE_DIM_KEY
 , FP.MARKET_DIMENSION_DIM_KEY
 , FP.CUSTOMER_SEGMENT_DIM_KEY
 , FP.BUSINESS_SECTOR_DIM_KEY
 , COI.LINE_OF_BUSINESS_DIM_KEY
 , FP.DURABLE_BROKER_HIERARCHY_KEY
 , FP.COVERAGE_CURRENCY_DIM_KEY as CURRENCY_DIM_KEY
 -- , BAD.AGENCY_CD
 , FP.DIM_POLICY_TERM_KEY
 ,FP.DIM_PROGRAM_CODE_DESC_KEY
 
 , case when inforce_flg=1 then ytd_gross_written_premium_amt else 0 end as ytd_inforce_premium_amt
          
FROM   DM.FACT_POLICY_CVRG_CD_PREMIUM_COMMISSION_MTHLY_AGGR FP

INNER JOIN DM.DIM_POLICY_TERM DPT
ON FP.DIM_POLICY_TERM_KEY = DPT.DIM_POLICY_TERM_KEY

INNER JOIN DM.MONTH_DIM MD
ON MD.MONTH_KEY = FP.ACCOUNTING_MONTH_KEY

INNER JOIN DM.dim_broker_policy_status_work DPTP
ON FP.DIM_POLICY_TERM_DURABLE_KEY = DPTP.DIM_POLICY_TERM_DURABLE_KEY
AND MD.MONTH_END_DATE BETWEEN TO_DATE(DPTP.EFFECTIVE_START_TS) AND TO_DATE(DPTP.EFFECTIVE_END_TS)

INNER JOIN DM.CLASS_OF_INSURANCE_DIM COI
ON FP.CLASS_OF_INSURANCE_DIM_KEY = COI.CLASS_OF_INSURANCE_DIM_KEY

INNER JOIN DM.DIM_BROKER_HIERARCHY DBH
ON FP.DURABLE_BROKER_HIERARCHY_KEY = DBH.DURABLE_BROKER_HIERARCHY_KEY
 and dbh.current_ind = upper('Y')
 
LEFT JOIN DM.BROKER_AGENCY_DIM BAD
ON BAD.DURABLE_BROKER_AGENCY_DIM_KEY = DBH.DURABLE_BROKER_AGENCY_DIM_KEY
AND BAD.BROKER_AGENCY_DIM_KEY = DBH.BROKER_AGENCY_DIM_KEY

LEFT JOIN DM.FACT_POLICY_RETENTION_MONTHLY_SNAPSHOT R
        ON FP.DIM_POLICY_TERM_KEY = R.DIM_POLICY_TERM_KEY
       AND FP.ACCOUNTING_MONTH_KEY = R.MONTH_KEY
       
LEFT JOIN  DM.FACT_ACTUAL_COUNT FAC
ON FP.DIM_POLICY_TERM_KEY = FAC.DIM_POLICY_TERM_KEY
AND FP.ACCOUNTING_MONTH_KEY = FAC.MONTH_KEY        
       
WHERE-- POLICY_NUMBER ='P04099165' AND 
FP.ACCOUNTING_MONTH_KEY =1513 AND dpt.POLICY_NUMBER <>'_NA_EDW' AND DPT.POLICY_NUMBER IS NOT NULL  
GROUP BY all                      
{% endset %}

{% set b_query %}
select
	concat_ws('|' , MONTH_KEY, POLICY_NUMBER, DIM_POLICY_TERM_KEY, LINE_OF_BUSINESS_DIM_KEY) as primary_id,
      MONTH_KEY
  , POLICY_NUMBER
  , POLICY_TERM_NUMBER as TERM_NUMBER
  , SUM(YTD_GROSS_WRITTEN_PREMIUM_AMT) AS YTD_GROSS_WRITTEN_PREMIUM_AMT
, SUM(YTD_GROSS_EARNED_PREMIUM_AMT)  AS YTD_GROSS_EARNED_PREMIUM_AMT
, SUM(YTD_NEW_BUSINESS_WRITTEN_PREMIUM_AMT)  AS YTD_NEW_BUSINESS_WRITTEN_PREMIUM_AMT  
, SUM (YTD_CANCELLED_PREMIUM_AMT) AS YTD_CANCELLED_PREMIUM_AMT
,SUM (YTD_LAPSED_PREMIUM_AMT) AS YTD_LAPSED_PREMIUM_AMT
,YTD_COMMISSION_AMT
,YTD_RENEWABLE_PREMIUM_AMT
,YTD_RETENTION_PREMIUM_AMT
,RENEWABLE_FLG
,RETENTION_FLG
,CANCELLED_FLG
,LAPSED_FLG
,NB_POLICY_FLG
,INFORCE_FLG
  , POLICY_EFFECTIVE_DATE
  , POLICY_EXPIRY_DATE
  , FUNCTIONAL_ENTITY_DIM_KEY
  , BUSINESS_TYPE_DIM_KEY
  , MARKET_DIMENSION_DIM_KEY
  , CUSTOMER_SEGMENT_DIM_KEY
  , BUSINESS_SECTOR_DIM_KEY
  , LINE_OF_BUSINESS_DIM_KEY
  , DURABLE_BROKER_HIERARCHY_KEY
  , CURRENCY_DIM_KEY
  -- , AGENCY_CODE
  , DIM_POLICY_TERM_KEY
  ,DIM_PROGRAM_CODE_DESC_KEY
  
  , ytd_inforce_premium_amt
  
  FROM DM.FACT_BROKER_MTHLY_SUMMARY
WHERE-- POLICY_NUMBER ='P04099165' AND 
MONTH_KEY =1513  AND POLICY_NUMBER IS NOT NULL and POLICY_NUMBER <>'_NA_EDW'
group by all
{% endset %}

{% for column_name in column_names %}

{% set audit_query = audit_helper.compare_column_values_verbose(
  a_query=a_query,
  b_query=b_query,
  primary_key="primary_id",
  column_to_compare=column_name
) %}

/*  Create a query combining results from all columns so that the user, or the test suite, can examine all at once. */

{% if loop.first %}

/*  Create a CTE that wraps all the unioned subqueries that are created	in this for loop */
  with main as ( 

{% endif %}

/*  There will be one audit_query subquery for each column */
( {{ audit_query }} )

{% if not loop.last %}

  union all

{% else %}

), 

  {%- if summarize %}

	final as (
	  select
		upper(column_name) as column_name,
		sum(case when conflicting_values then 1 else 0 end) as conflicting_values,
		sum(case when perfect_match then 1 else 0 end) as perfect_match,
		sum(case when null_in_a then 1 else 0 end) as nulls_in_source,
		sum(case when null_in_b then 1 else 0 end) as nulls_in_target,
		sum(case when missing_from_a then 1 else 0 end) as missing_from_source,
		sum(case when missing_from_b then 1 else 0 end) as missing_from_target
	  from main
	  group by 1
	  order by column_name
	)

  {%- else %}

	final as (
	  select
		primary_key,           
		upper(column_name) as column_name,
		conflicting_values,
		perfect_match,
		nulls_in_source,
		nulls_in_target,
		missing_from_source,
		missing_from_target
	  from main    
	  order by primary_key
	)

  {%- endif %}

  select * from final 
  order by conflicting_values desc;

{% endif %}

{% endfor %}

