
{% set column_names = [ 
"ACCESSMODE",
"ADDRESS1_ADDRESSID",
"ADDRESS1_ADDRESSTYPECODE",
"ADDRESS1_CITY",
"ADDRESS1_COMPOSITE",
"ADDRESS1_COUNTRY",
"ADDRESS1_COUNTY",
"ADDRESS1_FAX",
"ADDRESS1_LATITUDE",
"ADDRESS1_LINE1",
"ADDRESS1_LINE2",
"ADDRESS1_LINE3",
"ADDRESS1_LONGITUDE",
"ADDRESS1_NAME",
"ADDRESS1_POSTALCODE",
"ADDRESS1_POSTOFFICEBOX",
"ADDRESS1_SHIPPINGMETHODCODE",
"ADDRESS1_STATEORPROVINCE",
"ADDRESS1_TELEPHONE1",
"ADDRESS1_TELEPHONE2",
"ADDRESS1_TELEPHONE3",
"ADDRESS1_UPSZONE",
"ADDRESS1_UTCOFFSET",
"ADDRESS2_ADDRESSID",
"ADDRESS2_ADDRESSTYPECODE",
"ADDRESS2_CITY",
"ADDRESS2_COMPOSITE",
"ADDRESS2_COUNTRY",
"ADDRESS2_COUNTY",
"ADDRESS2_FAX",
"ADDRESS2_LATITUDE",
"ADDRESS2_LINE1",
"ADDRESS2_LINE2",
"ADDRESS2_LINE3",
"ADDRESS2_LONGITUDE",
"ADDRESS2_NAME",
"ADDRESS2_POSTALCODE",
"ADDRESS2_POSTOFFICEBOX",
"ADDRESS2_SHIPPINGMETHODCODE",
"ADDRESS2_STATEORPROVINCE",
"ADDRESS2_TELEPHONE1",
"ADDRESS2_TELEPHONE2",
"ADDRESS2_TELEPHONE3",
"ADDRESS2_UPSZONE",
"ADDRESS2_UTCOFFSET",
"BUSINESSUNITID",
"BUSINESSUNITIDNAME",
"CALENDARID",
"CALTYPE",
"CREATEDBY",
"CREATEDBYNAME",
"CREATEDBYYOMINAME",
"CREATEDON",
"CREATEDONBEHALFBY",
"CREATEDONBEHALFBYNAME",
"CREATEDONBEHALFBYYOMINAME",
"DEFAULTFILTERSPOPULATED",
"DEFAULTMAILBOX",
"DEFAULTMAILBOXNAME",
"DISABLEDREASON",
"DISPLAYINSERVICEVIEWS",
"DOMAINNAME",
"EMAILROUTERACCESSAPPROVAL",
"EMPLOYEEID",
"ENTITYIMAGEID",
"ENTITYIMAGE_TIMESTAMP",
"ENTITYIMAGE_URL",
"EXCHANGERATE",
"FIRSTNAME",
"FULLNAME",
"GOVERNMENTID",
"HOMEPHONE",
"IMPORTSEQUENCENUMBER",
"INCOMINGEMAILDELIVERYMETHOD",
"INTERNALEMAILADDRESS",
"INVITESTATUSCODE",
"ISDISABLED",
"ISEMAILADDRESSAPPROVEDBYO365ADMIN",
"ISINTEGRATIONUSER",
"ISLICENSED",
"ISSYNCWITHDIRECTORY",
"JOBTITLE",
"LASTNAME",
"MIDDLENAME",
"MOBILEALERTEMAIL",
"MOBILEPHONE",
"MODIFIEDBY",
"MODIFIEDBYNAME",
"MODIFIEDBYYOMINAME",
"MODIFIEDON",
"MODIFIEDONBEHALFBY",
"MODIFIEDONBEHALFBYNAME",
"MODIFIEDONBEHALFBYYOMINAME",
"NICKNAME",
"ORGANIZATIONID",
"ORGANIZATIONIDNAME",
"OUTGOINGEMAILDELIVERYMETHOD",
"OVERRIDDENCREATEDON",
"PARENTSYSTEMUSERID",
"PARENTSYSTEMUSERIDNAME",
"PARENTSYSTEMUSERIDYOMINAME",
"PASSPORTHI",
"PASSPORTLO",
"PERSONALEMAILADDRESS",
"PHOTOURL",
"POSITIONID",
"POSITIONIDNAME",
"PREFERREDADDRESSCODE",
"PREFERREDEMAILCODE",
"PREFERREDPHONECODE",
"PROCESSID",
"QUEUEID",
"QUEUEIDNAME",
"SALUTATION",
"SETUPUSER",
"SITEID",
"SITEIDNAME",
"SKILLS",
"STAGEID",
"SYSTEMUSERID",
"TERRITORYID",
"TERRITORYIDNAME",
"TIMEZONERULEVERSIONNUMBER",
"TITLE",
"TRANSACTIONCURRENCYID",
"TRANSACTIONCURRENCYIDNAME",
"TRAVERSEDPATH",
"USERLICENSETYPE",
"UTCCONVERSIONTIMEZONECODE",
"WINDOWSLIVEID",
"YAMMEREMAILADDRESS",
"YAMMERUSERID",
"YOMIFIRSTNAME",
"YOMIFULLNAME",
"YOMILASTNAME",
"YOMIMIDDLENAME"
] %} 
{% set summarize = true %} 

{% set a_query %} 
SELECT * FROM STG.ST_D365_SYSTEMUSER
QUALIFY ROW_NUMBER() OVER(PARTITION BY SYSTEMUSERID ORDER BY INSERT_TS DESC, UNIQUE_KEY DESC) = 1
{% endset %} 

{% set b_query %} 
SELECT * FROM STG.ST_NBDYNAMICS_FILTEREDSYSTEMUSER
QUALIFY ROW_NUMBER() OVER(PARTITION BY SYSTEMUSERID ORDER BY INSERT_TS DESC, UNIQUE_KEY DESC) = 1
{% endset %} 


{% for column_name in column_names %}

{% set audit_query = audit_helper.compare_column_values_verbose(
  a_query=a_query,
  b_query=b_query,
  primary_key="SYSTEMUSERID",
  column_to_compare=column_name
) %}


{% if loop.first %}

with main as ( 

{% endif %}

( {{ audit_query }} )

{% if not loop.last %}

  union all

{% else %}

), 

  {%- if summarize %}

	final as (
	  select
		upper(column_name) as column_name,
		sum(case when conflicting_values then 1 else 0 end) as conflicting_values,
		sum(case when perfect_match then 1 else 0 end) as perfect_match,
		sum(case when null_in_a then 1 else 0 end) as nulls_in_source,
		sum(case when null_in_b then 1 else 0 end) as nulls_in_target,
		sum(case when missing_from_a then 1 else 0 end) as missing_from_source,
		sum(case when missing_from_b then 1 else 0 end) as missing_from_target
	  from main
	  group by 1
	  order by column_name
	)

  {%- else %}

	final as (
	  select
		primary_key,           
		upper(column_name) as column_name,
		conflicting_values,
		perfect_match,
		nulls_in_source,
		nulls_in_target,
		missing_from_source,
		missing_from_target
	  from main    
	  order by primary_key
	)

  {%- endif %}

  select * from final 
  order by conflicting_values desc;

{% endif %}

{% endfor %}

