
{% set column_names = [
"ACCOUNTCATEGORYCODE",
"ACCOUNTCLASSIFICATIONCODE",
"ACCOUNTID",
"ACCOUNTNUMBER",
"ACCOUNTRATINGCODE",
"ADDRESS1_ADDRESSID",
"ADDRESS1_ADDRESSTYPECODE",
"ADDRESS1_CITY",
"ADDRESS1_COMPOSITE",
"ADDRESS1_COUNTRY",
"ADDRESS1_COUNTY",
"ADDRESS1_FAX",
"ADDRESS1_FREIGHTTERMSCODE",
"ADDRESS1_LATITUDE",
"ADDRESS1_LINE1",
"ADDRESS1_LINE2",
"ADDRESS1_LINE3",
"ADDRESS1_LONGITUDE",
"ADDRESS1_NAME",
"ADDRESS1_POSTALCODE",
"ADDRESS1_POSTOFFICEBOX",
"ADDRESS1_PRIMARYCONTACTNAME",
"ADDRESS1_SHIPPINGMETHODCODE",
"ADDRESS1_STATEORPROVINCE",
"ADDRESS1_TELEPHONE1",
"ADDRESS1_TELEPHONE2",
"ADDRESS1_TELEPHONE3",
"ADDRESS1_UPSZONE",
"ADDRESS1_UTCOFFSET",
"ADDRESS2_ADDRESSID",
"ADDRESS2_ADDRESSTYPECODE",
"ADDRESS2_CITY",
"ADDRESS2_COMPOSITE",
"ADDRESS2_COUNTRY",
"ADDRESS2_COUNTY",
"ADDRESS2_FAX",
"ADDRESS2_FREIGHTTERMSCODE",
"ADDRESS2_LATITUDE",
"ADDRESS2_LINE1",
"ADDRESS2_LINE2",
"ADDRESS2_LINE3",
"ADDRESS2_LONGITUDE",
"ADDRESS2_NAME",
"ADDRESS2_POSTALCODE",
"ADDRESS2_POSTOFFICEBOX",
"ADDRESS2_PRIMARYCONTACTNAME",
"ADDRESS2_SHIPPINGMETHODCODE",
"ADDRESS2_STATEORPROVINCE",
"ADDRESS2_TELEPHONE1",
"ADDRESS2_TELEPHONE2",
"ADDRESS2_TELEPHONE3",
"ADDRESS2_UPSZONE",
"ADDRESS2_UTCOFFSET",
"AGING30",
"AGING30_BASE",
"AGING60",
"AGING60_BASE",
"AGING90",
"AGING90_BASE",
"BUSINESSTYPECODE",
"CREATEDBY",
"CREATEDBYNAME",
"CREATEDBYYOMINAME",
"CREATEDON",
"CREATEDONBEHALFBY",
"CREATEDONBEHALFBYNAME",
"CREATEDONBEHALFBYYOMINAME",
"CREDITLIMIT",
"CREDITLIMIT_BASE",
"CREDITONHOLD",
"CUSTOMERSIZECODE",
"CUSTOMERTYPECODE",
"DEFAULTPRICELEVELID",
"DEFAULTPRICELEVELIDNAME",
"DESCRIPTION",
"DONOTBULKEMAIL",
"DONOTBULKPOSTALMAIL",
"DONOTEMAIL",
"DONOTFAX",
"DONOTPHONE",
"DONOTPOSTALMAIL",
"DONOTSENDMM",
"EMAILADDRESS1",
"EMAILADDRESS2",
"EMAILADDRESS3",
"ENTITYIMAGEID",
"ENTITYIMAGE_TIMESTAMP",
"ENTITYIMAGE_URL",
"EXCHANGERATE",
"FAX",
"FTPSITEURL",
"IMPORTSEQUENCENUMBER",
"INDUSTRYCODE",
"LASTUSEDINCAMPAIGN",
"MARKETCAP",
"MARKETCAP_BASE",
"MASTERACCOUNTIDNAME",
"MASTERACCOUNTIDYOMINAME",
"MASTERID",
"MERGED",
"MODIFIEDBY",
"MODIFIEDBYNAME",
"MODIFIEDBYYOMINAME",
"MODIFIEDON",
"MODIFIEDONBEHALFBY",
"MODIFIEDONBEHALFBYNAME",
"MODIFIEDONBEHALFBYYOMINAME",
"NAME",
"NEW_ADDITIONAL_CLIENT_NAMES",
"NEW_COMPANYTYPE",
"NEW_COMPANY_OPERATING_NAME",
"NEW_CUSTOMERBROKERNUMBER",
"NEW_CUSTOMERCONSECUTIVEYEARS",
"NEW_CUSTOMERINCEPTIONYEAR",
"NEW_CUSTOMERLEADUNDERWRITER",
"NEW_CUSTOMERLEADUNDERWRITERNAME",
"NEW_CUSTOMERLEADUNDERWRITERYOMINAME",
"NEW_CUSTOMERSIGNATURESERVICEFLAG",
"NEW_CUSTOMERSTATUS",
"NEW_CUSTOMERTERMINATIONCODE",
"NEW_DONOTSOLICIT",
"NEW_EXECUTIVERELATIONSHIPMANAGER",
"NEW_EXECUTIVERELATIONSHIPMANAGERNAME",
"NEW_EXECUTIVERELATIONSHIPMANAGERYOMINAME",
"NEW_GOOGLEMAP",
"NEW_LANGUAGE_PREFERENCE_CD",
"NEW_LEGACY_CUSTOMER_NAME",
"NEW_LEGALNAME",
"NEW_LOSTTOINSURER",
"NEW_LOSTTOINSURERNAME",
"NEW_LOSTTOINSURERYOMINAME",
"NEW_MAIL_ADDRESS_PROVINCE",
"NEW_MAIL_ADDRESS_RR",
"NEW_MAIL_ADDRESS_STREET_DIRECTION",
"NEW_MAIL_ADDRESS_STREET_NAME",
"NEW_MAIL_ADDRESS_STREET_NUMBER",
"NEW_MAIL_ADDRESS_STREET_TYPE",
"NEW_MAIL_ADDRESS_SUITE_UNIT",
"NEW_MAIL_ADDRESS_OTHER_PROVINCE",
"NEW_OTHER_PHONE_DESCRIPTION",
"NEW_SPECIALCLAIMSHANDLING",
"NEW_STREET_ADDRESS_LINE_1",
"NEW_STREET_ADDRESS_LINE_2",
"NEW_SUBMISSION_ID",
"NEW_TOLLFREEPHONE",
"NEW_YEARESTABLISHED",
"NUMBEROFEMPLOYEES",
"OPENDEALS",
"OPENDEALS_DATE",
"OPENDEALS_STATE",
"OPENREVENUE",
"OPENREVENUE_BASE",
"OPENREVENUE_DATE",
"OPENREVENUE_STATE",
"ORIGINATINGLEADID",
"ORIGINATINGLEADIDNAME",
"ORIGINATINGLEADIDYOMINAME",
"OVERRIDDENCREATEDON",
"OWNERID",
"OWNERIDNAME",
"OWNERIDTYPE",
"OWNERIDYOMINAME",
"OWNERSHIPCODE",
"OWNINGBUSINESSUNIT",
"OWNINGTEAM",
"OWNINGUSER",
"PARENTACCOUNTID",
"PARENTACCOUNTIDNAME",
"PARENTACCOUNTIDYOMINAME",
"PARTICIPATESINWORKFLOW",
"PAYMENTTERMSCODE",
"PREFERREDAPPOINTMENTDAYCODE",
"PREFERREDAPPOINTMENTTIMECODE",
"PREFERREDCONTACTMETHODCODE",
"PREFERREDEQUIPMENTID",
"PREFERREDEQUIPMENTIDNAME",
"PREFERREDSERVICEID",
"PREFERREDSERVICEIDNAME",
"PREFERREDSYSTEMUSERID",
"PREFERREDSYSTEMUSERIDNAME",
"PREFERREDSYSTEMUSERIDYOMINAME",
"PRIMARYCONTACTID",
"PRIMARYCONTACTIDNAME",
"PRIMARYCONTACTIDYOMINAME",
"PROCESSID",
"REVENUE",
"REVENUE_BASE",
"SHARESOUTSTANDING",
"SHIPPINGMETHODCODE",
"SIC",
"STAGEID",
"STATECODE",
"STATUSCODE",
"STOCKEXCHANGE",
"TELEPHONE1",
"TELEPHONE2",
"TELEPHONE3",
"TERRITORYCODE",
"TERRITORYID",
"TERRITORYIDNAME",
"TICKERSYMBOL",
"TIMEZONERULEVERSIONNUMBER",
"TRANSACTIONCURRENCYID",
"TRANSACTIONCURRENCYIDNAME",
"TRAVERSEDPATH",
"UTCCONVERSIONTIMEZONECODE",
"WEBSITEURL",
"YOMINAME"
] %}
{% set summarize = true %}

{% set a_query %}      
SELECT * FROM STG.ST_D365_ACCOUNT
QUALIFY ROW_NUMBER() OVER(PARTITION BY ACCOUNTID ORDER BY INSERT_TS DESC, UNIQUE_KEY DESC) = 1
{% endset %}


{% set b_query %}
SELECT * FROM STG.ST_NBDYNAMICS_FILTEREDACCOUNT
QUALIFY ROW_NUMBER() OVER(PARTITION BY ACCOUNTID ORDER BY INSERT_TS DESC, UNIQUE_KEY DESC) = 1
{% endset %}

{% for column_name in column_names %}

{% set audit_query = audit_helper.compare_column_values_verbose(
  a_query=a_query,
  b_query=b_query,
  primary_key="ACCOUNTID",
  column_to_compare=column_name
) %}


{% if loop.first %}

with main as ( 

{% endif %}

( {{ audit_query }} )

{% if not loop.last %}

  union all

{% else %}

), 

  {%- if summarize %}

	final as (
	  select
		upper(column_name) as column_name,
		sum(case when conflicting_values then 1 else 0 end) as conflicting_values,
		sum(case when perfect_match then 1 else 0 end) as perfect_match,
		sum(case when null_in_a then 1 else 0 end) as nulls_in_source,
		sum(case when null_in_b then 1 else 0 end) as nulls_in_target,
		sum(case when missing_from_a then 1 else 0 end) as missing_from_source,
		sum(case when missing_from_b then 1 else 0 end) as missing_from_target
	  from main
	  group by 1
	  order by column_name
	)

  {%- else %}

	final as (
	  select
		primary_key,           
		upper(column_name) as column_name,
		conflicting_values,
		perfect_match,
		nulls_in_source,
		nulls_in_target,
		missing_from_source,
		missing_from_target
	  from main    
	  order by primary_key
	)

  {%- endif %}

  select * from final 
  order by conflicting_values desc;

{% endif %}

{% endfor %}

